#!/bin/sh
#
# /etc/rc.d/haveged: start/stop haveged#

case $1 in
start)
	/usr/sbin/haveged
	;;
stop)
  test -f /var/run/haveged.pid && kill $(< /var/run/haveged.pid)
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
